SHARED_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/shared"

GENERATED_HEADER='###
### DO NOT MODIFY THIS FILE.  THIS FILE HAS BEEN AUTOGENERATED
###
'

function render_dockerfile_template() {
  TEMP=$(mktemp)
  printf "%s\n" "${IMAGE_CUSTOMIZATIONS}" > $TEMP

  TEMPLATE_PATH="${SHARED_DIR}"/Dockerfile.tpl

  echo "$GENERATED_HEADER"

  cat "$TEMPLATE_PATH" | \
    sed "s|{{BASE_IMAGE}}|$BASE_IMAGE|g" | \
    sed "/# BEGIN IMAGE CUSTOMIZATIONS/ r $TEMP"

  rm "$TEMP"
}

render_dockerfile_template > Dockerfile
